---
title: "Remesas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Librerías



```{r}
library(tidyverse)     ## data wrangling + ggplot2
library(colorspace)    ## adjust colors
library(ggforce)       ## sina plots
library(ggdist)        ## halfeye plots
library(ggridges)      ## ridgeline plots
library(ggbeeswarm)    ## beeswarm plots
library(gghalves)      ## off-set jitter
library(systemfonts)   ## custom fonts
library(readxl)        ## read data
library(extrafont)     
## custom colors
```


```{r}
## general theme

theme_set(theme_void(base_family = "Garamond"))


theme_update(
  axis.text.x = element_text(color = "black", face = "bold", size = 10,
                             margin = margin(t = 6)),
  axis.text.y = element_text(color = "black", size = 10, hjust = 1,
                             margin = margin(r = 6), family = "Garamond"),
  axis.line.x = element_line(color = "black", size = 1),
  #panel.grid.major.y = element_line(color = "grey90", size = .6),
  plot.background = element_rect(fill = "white", color = "white"),
  plot.margin = margin(rep(20, 4))

)

```


```{r eval=FALSE, include=FALSE}
my_pal <- rcartocolor::carto_pal(n = 12, name = "Bold")[c(8,5, 2, 12, 1,7,3,4,6,9,10,11)]
```


```{r}
my_pal <- c(rep("#222222",4),"#B857E5",rep("#222222",7))
```




## Datos


```{r}
BASE <- read_excel("BASE.xlsx", col_types = c("date", 
    "text", "numeric", "numeric"))
```

```{r}
BASE$MES<-factor(BASE$MES,levels =c('Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'))
```



```{r}

g1 <- BASE  %>%

  ggplot(aes(x = as.factor(MES), y = REMESAS, color = as.factor(MES), fill = as.factor(MES))) +
  scale_color_manual(values = my_pal, guide = "none") +
  scale_fill_manual(values = my_pal, guide = "none")

g1 <- g1 +
  geom_boxplot(alpha = .5, size = 1.5, outlier.size = 3) +
  scale_y_continuous(labels=function(x) format(x, big.mark = ",", scientific = FALSE)) + theme(legend.position="none")


g1 + ggtitle("Remesas totales por mes")

```

 








